#!/usr/bin/env python3
"""Run a directory of concrete experiment configs (generated by make_grid).

Usage examples:
  # Sequential
  python -m pipeline.run_configs --configs sweeps/reinforce_unified_demo/configs \
      --output results/reinforce_unified_demo

  # Parallel (4 workers)
  python -m pipeline.run_configs --configs sweeps/reinforce_unified_demo/configs \
      --output results/reinforce_unified_demo --parallel 4

  # Dry run (print commands only)
  python -m pipeline.run_configs --configs sweeps/reinforce_unified_demo/configs --dry-run

Skips a run if an output parquet file already exists (unless --force).
"""
from __future__ import annotations

import argparse
import concurrent.futures as cf
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import List

# Parquet filename pattern used by one_camp_n_days_v2 (epoch_agg__<run_id>.parquet)
# We cannot know run_id ahead of time; we use label presence in existing parquet filenames directory
# OR simply skip existence check unless user implements a manifest. For now we skip duplication by
# checking a stamp file.
STAMP_NAME = "_RUN_COMPLETE.stamp"


def _discover_configs(cfg_dir: Path) -> List[Path]:
    return sorted([p for p in cfg_dir.glob('*.yaml') if p.is_file()])


def _build_command(cfg_path: Path, output_dir: Path) -> List[str]:
    return [
        sys.executable, '-m', 'derby.experiments.one_camp_n_days_v2',
        '--config', str(cfg_path),
        '-o', str(output_dir)
    ]


def _run_one(cfg_path: Path, output_dir: Path, force: bool, dry_run: bool) -> dict:
    run_dir = output_dir / cfg_path.stem  # isolate each run's artifacts
    run_dir.mkdir(parents=True, exist_ok=True)
    stamp = run_dir / STAMP_NAME
    if stamp.exists() and not force:
        return {"config": str(cfg_path), "status": "skipped"}
    cmd = _build_command(cfg_path, run_dir)
    if dry_run:
        return {"config": str(cfg_path), "status": "dry-run", "cmd": ' '.join(cmd)}
    try:
        proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if proc.returncode == 0:
            stamp.write_text("ok")
            return {"config": str(cfg_path), "status": "ok"}
        else:
            return {"config": str(cfg_path), "status": "failed", "rc": proc.returncode, "stderr": proc.stderr[-5000:]}
    except Exception as e:  # pragma: no cover
        return {"config": str(cfg_path), "status": "error", "error": str(e)}


def main():
    ap = argparse.ArgumentParser(description="Run a directory of generated configs")
    ap.add_argument('--configs', required=True, help='Directory containing run_*.yaml configs')
    ap.add_argument('--output', required=True, help='Directory root for per-run outputs')
    ap.add_argument('--parallel', type=int, default=1, help='Number of parallel workers (default 1)')
    ap.add_argument('--force', action='store_true', help='Re-run even if stamp present')
    ap.add_argument('--dry-run', action='store_true', help='Print commands without executing')
    ap.add_argument('--json', dest='json_out', action='store_true', help='Print JSON summary at end')
    args = ap.parse_args()

    cfg_dir = Path(args.configs)
    if not cfg_dir.is_dir():
        raise SystemExit(f"Config directory not found: {cfg_dir}")
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    configs = _discover_configs(cfg_dir)
    if not configs:
        print("No configs discovered", file=sys.stderr)
        return
    print(f"[run_configs] Discovered {len(configs)} configs in {cfg_dir}")

    results = []
    if args.parallel <= 1:
        for p in configs:
            r = _run_one(p, output_dir, args.force, args.dry_run)
            results.append(r)
            print(f"{p.name}: {r['status']}")
    else:
        with cf.ThreadPoolExecutor(max_workers=args.parallel) as ex:
            fut_map = {ex.submit(_run_one, p, output_dir, args.force, args.dry_run): p for p in configs}
            for fut in cf.as_completed(fut_map):
                r = fut.result()
                results.append(r)
                cfg_name = Path(r['config']).name
                print(f"{cfg_name}: {r['status']}")

    # Summary
    counts = {}
    for r in results:
        counts[r['status']] = counts.get(r['status'], 0) + 1
    print("Summary:", counts)

    if args.json_out:
        print(json.dumps({"results": results, "summary": counts}, indent=2))


if __name__ == '__main__':
    main()
