# Base configuration for Derby sweep (consumed by _run_simple_config)
label: sweep-demo
setup: setup_1
num_days: 1
num_trajs: 50
num_epochs: 5
debug: false
agents:
  - name: agent1
    policy: REINFORCE_Gaussian_v2_MarketEnv_Continuous
    params:
      learning_rate: 0.001
      shape_reward: false
  - name: agent2
    policy: FixedBidPolicy
    params:
      bid_per_item: 5
      total_limit: 5
