# Parameter grid using dotted keys; values are lists to sweep over
setup: [setup_1]
num_days: [1]
num_trajs: [200]
num_epochs: [100]
agents.0.policy: [
  REINFORCE_Gaussian_v2_MarketEnv_Continuous,
  REINFORCE_Gaussian_v3_MarketEnv_Continuous
]
agents.0.params.learning_rate: [1e-6, 5e-7]
agents.0.params.shape_reward: [False]
