num_days: 1
num_trajs: 200
num_epochs: 10
setup: setup_1
agents:
  - name: agent1
    policy: REINFORCE_Gaussian_v2_MarketEnv_Continuous
    params:
      learning_rate: 5e-7
      shape_reward: false
  - name: agent2
    policy: FixedBidPolicy
    params:
      bid_per_item: 5
      total_limit: 5
